Numpy - Linear Algebra library

    - used for performing math and logical operations

    - provides features for matrix operations

    - faster than list

## Speed

In [5]:
import math
import numpy as np
import torch
import tensorflow as tf

In [3]:
arr = np.random.rand(100000000)

l = list(arr)

torch_arr = torch.tensor(arr)

a = tf.constant(arr, dtype = tf.float64)

In [6]:
%timeit list(map(math.sqrt,l))

11.9 s ± 1.76 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
%timeit np.sqrt(arr)

307 ms ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Numpy -> 4byte ( just the no.)

List -> 28byte (Object value, type, reference count, size)

Numpy is contiguous Memory ,SIMD Vector Processing, Effective Utilization

## Numpy 

In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])

In [10]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [28]:
arr = np.array([1,2,3], dtype = 'float64')

## Basic Numpy Attributes

In [29]:
print("data_type:",arr.dtype)
print("arr_shape:", arr.shape)
print("arr_dimension:", arr.ndim)
print("arr_size:", arr.size)
print("iem_size:", arr.itemsize)
print("arr_size:", arr.nbytes)

data_type: float64
arr_shape: (3,)
arr_dimension: 1
arr_size: 3
iem_size: 8
arr_size: 24


In [32]:
arr = np.array([1,2,'sas'])
arr

array(['1', '2', 'sas'], dtype='<U11')

## MultiDimension

In [36]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [39]:
arr = np.array([[1,2,3],[4,5,6]]) #matrix
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
print("data_type:",arr.dtype)
print("arr_shape:", arr.shape)
print("arr_dimension:", arr.ndim)
print("arr_size:", arr.size)
print("iem_size:", arr.itemsize)
print("arr_size:", arr.nbytes)

data_type: int32
arr_shape: (2, 3)
arr_dimension: 2
arr_size: 6
iem_size: 4
arr_size: 24


## Accessing Elements of array

In [41]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
print(a[1][2])
print(a[1,2])
print(a[-1,-2])

7
7
7


In [46]:
print(a[1,1:]) #return object is also an array

[6 7 8]


In [52]:
#modify data
a[1,2] = 10
a

array([[ 1,  2,  3,  4],
       [ 5,  0, 10,  0]])

In [53]:
a[1,1:] = [6,7,8]
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
# numpy has broadcasting
a[1,1:] = 0
a

array([[1, 2, 3, 4],
       [5, 0, 0, 0]])

## Matrix Generation

In [57]:
print(np.zeros(3))
print(np.zeros((3,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
print(np.ones(3))

[1. 1. 1.]


In [62]:
temp = np.full((4,4),10)
temp

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [63]:
np.full_like(temp,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [64]:
np.random.rand(4,2)

array([[0.73817099, 0.55125814],
       [0.54230403, 0.83524261],
       [0.57878342, 0.2436797 ],
       [0.11154257, 0.67565337]])

In [66]:
np.random.randint(10,16,size=(3,4))

array([[13, 12, 11, 15],
       [14, 10, 13, 11],
       [13, 13, 11, 10]])

In [67]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
arr = np.array([[1,2]])
arr.shape

(1, 2)

In [72]:
r1 = np.repeat(arr,5, axis=0)
r1

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [74]:
c = r1.copy()
c

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [75]:
cr1 = r1
cr1[0,0] = 10
r1

array([[10,  2],
       [ 1,  2],
       [ 1,  2],
       [ 1,  2],
       [ 1,  2]])

In [80]:
#reference to the same object a=b
#shallow copy, a.copy() -> storing only the changed element 
#deep copy -> storing an entire new copy   import copy.deepcopy

In [79]:
c = r1.copy()
c

array([[10,  2],
       [ 1,  2],
       [ 1,  2],
       [ 1,  2],
       [ 1,  2]])

### Reshape

In [82]:
random = np.random.randn(8)

In [85]:
random.reshape(4,2)

array([[ 1.4016075 ,  0.01485411],
       [-0.99152195, -0.66392162],
       [-0.65047858, -0.11321547],
       [-0.36153065, -0.1598748 ]])

### Stacking

In [86]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [90]:
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [91]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Math Operations

In [93]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [103]:
print("Sum:",a + b)
print("Mul:",a * b)
print("Sqrt:",a ** b)
print("Div:",a / b)

Sum: [ 6  8 10 12]
Mul: [ 5 12 21 32]
Sqrt: [    1    64  2187 65536]
Div: [0.2        0.33333333 0.42857143 0.5       ]


In [108]:
c = np.ones((2,4))
print("c:\n", c)

print("Broadcasting:\n", a * c)

c:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Broadcasting:
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [110]:
#Trignometry
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Matrix Operation

In [111]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [112]:
a @ b

array([[6., 6.],
       [6., 6.]])

In [113]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [116]:
c = np.matmul(a,b)

In [117]:
np.linalg.det(c)

0.0

In [123]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Stats

In [118]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))
print(np.cumsum(stats))
print(np.cumprod(stats))
print(np.mean(stats))
print(np.median(stats))

1
6
21
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]
3.5
3.5


In [122]:
print(np.max(stats, axis=1))

[3 6]


## Implementing Math Function

In [124]:
y = [34, 3, 7, 8, 3]
y_hat = [66, 1, 9, 5, 1]

In [125]:
y_np = np.array(y)
y_hat_np = np.array(y_hat)

In [129]:
np.mean(np.sum((y_np - y_hat_np) ** 2))

1045.0

In [130]:
a = [1,2,3,4,5]
np.mean(a)

3.0

In [131]:
np.std(a)

1.4142135623730951

In [134]:
((a - np.mean(a))/np.std(a))

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])